# Generated by Django 5.1.3 on 2024-11-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=34, verbose_name='Названия продукта')),
                ('brand', models.CharField(max_length=24, verbose_name='Бренд')),
                ('category', models.CharField(max_length=24, verbose_name='Категория')),
                ('price', models.PositiveBigIntegerField(default=0, verbose_name='Цена')),
                ('product_image', models.ImageField(upload_to='ProductImages/', verbose_name='Фото продукта')),
                ('sign', models.PositiveIntegerField(default=0, verbose_name='знак')),
            ],
        ),
    ]
